"""initial tenant-scoped domain"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8939170ed5ce"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "organization_members",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.CheckConstraint("role IN ('owner','admin','viewer')"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "user_id"),
    )
    op.create_table(
        "stores",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "organization_id"),
    )
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stores_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "vendors",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("vendor_code", sa.String(length=60), nullable=True),
        sa.Column("default_lead_time_days", sa.Integer(), nullable=False),
        sa.Column("minimum_order_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("default_lead_time_days >= 0"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "organization_id"),
        sa.UniqueConstraint("organization_id", "name"),
    )
    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vendors_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "import_jobs",
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("import_type", sa.String(length=20), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("rows_imported", sa.Integer(), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), nullable=False),
        sa.Column("rows_duplicate", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id", "organization_id"],
            ["stores.id", "stores.organization_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "import_type", "file_hash"),
    )
    with op.batch_alter_table("import_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_import_jobs_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("upc", sa.String(length=32), nullable=True),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("subcategory", sa.String(length=80), nullable=True),
        sa.Column("size", sa.String(length=40), nullable=False),
        sa.Column("units_per_case", sa.Integer(), nullable=False),
        sa.Column("default_vendor_id", sa.String(length=36), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("units_per_case > 0"),
        sa.ForeignKeyConstraint(
            ["default_vendor_id", "organization_id"],
            ["vendors.id", "vendors.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "organization_id"),
        sa.UniqueConstraint("organization_id", "sku"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_products_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "smart_orders",
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("vendor_id", sa.String(length=36), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("estimated_total_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("estimated_total_cost >= 0"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id", "organization_id"],
            ["stores.id", "stores.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id", "organization_id"],
            ["vendors.id", "vendors.organization_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "organization_id"),
    )
    with op.batch_alter_table("smart_orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_smart_orders_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "inventory_snapshots",
        sa.Column("snapshot_at", sa.Date(), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("retail_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("quantity_on_hand >= 0 AND retail_price >= 0"),
        sa.CheckConstraint("unit_cost IS NULL OR unit_cost >= 0"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id", "organization_id"],
            ["products.id", "products.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id", "organization_id"],
            ["stores.id", "stores.organization_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "source_key"),
    )
    with op.batch_alter_table("inventory_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_snapshots_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_snapshots_snapshot_at"), ["snapshot_at"], unique=False
        )
        batch_op.create_index(
            "ix_inventory_store_product", ["store_id", "product_id"], unique=False
        )

    op.create_table(
        "purchases",
        sa.Column("vendor_id", sa.String(length=36), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("quantity_units", sa.Integer(), nullable=False),
        sa.Column("quantity_cases", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("invoice_number", sa.String(length=100), nullable=True),
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("quantity_units > 0 AND unit_cost >= 0"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id", "organization_id"],
            ["products.id", "products.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id", "organization_id"],
            ["stores.id", "stores.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id", "organization_id"],
            ["vendors.id", "vendors.organization_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "source_key"),
    )
    with op.batch_alter_table("purchases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchases_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            "ix_purchases_store_product", ["store_id", "product_id"], unique=False
        )

    op.create_table(
        "reorder_recommendations",
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("vendor_id", sa.String(length=36), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_quantity", sa.Integer(), nullable=False),
        sa.Column("average_daily_demand", sa.Float(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("safety_stock", sa.Float(), nullable=False),
        sa.Column("reorder_point", sa.Float(), nullable=False),
        sa.Column("target_stock", sa.Float(), nullable=False),
        sa.Column("recommended_units", sa.Integer(), nullable=False),
        sa.Column("recommended_cases", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id", "organization_id"],
            ["products.id", "products.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id", "organization_id"],
            ["stores.id", "stores.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id", "organization_id"],
            ["vendors.id", "vendors.organization_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reorder_recommendations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reorder_recommendations_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "sales",
        sa.Column("sold_at", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("gross_revenue", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("transaction_id", sa.String(length=100), nullable=True),
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("quantity >= 0 AND gross_revenue >= 0"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id", "organization_id"],
            ["products.id", "products.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id", "organization_id"],
            ["stores.id", "stores.organization_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "source_key"),
    )
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sales_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sales_sold_at"), ["sold_at"], unique=False)
        batch_op.create_index("ix_sales_store_product", ["store_id", "product_id"], unique=False)

    op.create_table(
        "smart_order_lines",
        sa.Column("smart_order_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("recommended_units", sa.Integer(), nullable=False),
        sa.Column("recommended_cases", sa.Integer(), nullable=False),
        sa.Column("units_per_case", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("recommended_units >= 0 AND recommended_cases >= 0"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id", "organization_id"],
            ["products.id", "products.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["smart_order_id", "organization_id"],
            ["smart_orders.id", "smart_orders.organization_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("smart_order_id", "product_id"),
    )
    with op.batch_alter_table("smart_order_lines", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_smart_order_lines_organization_id"), ["organization_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("smart_order_lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_smart_order_lines_organization_id"))

    op.drop_table("smart_order_lines")
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.drop_index("ix_sales_store_product")
        batch_op.drop_index(batch_op.f("ix_sales_sold_at"))
        batch_op.drop_index(batch_op.f("ix_sales_organization_id"))

    op.drop_table("sales")
    with op.batch_alter_table("reorder_recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reorder_recommendations_organization_id"))

    op.drop_table("reorder_recommendations")
    with op.batch_alter_table("purchases", schema=None) as batch_op:
        batch_op.drop_index("ix_purchases_store_product")
        batch_op.drop_index(batch_op.f("ix_purchases_organization_id"))

    op.drop_table("purchases")
    with op.batch_alter_table("inventory_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_inventory_store_product")
        batch_op.drop_index(batch_op.f("ix_inventory_snapshots_snapshot_at"))
        batch_op.drop_index(batch_op.f("ix_inventory_snapshots_organization_id"))

    op.drop_table("inventory_snapshots")
    with op.batch_alter_table("smart_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_smart_orders_organization_id"))

    op.drop_table("smart_orders")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_organization_id"))

    op.drop_table("products")
    with op.batch_alter_table("import_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_jobs_organization_id"))

    op.drop_table("import_jobs")
    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vendors_organization_id"))

    op.drop_table("vendors")
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stores_organization_id"))

    op.drop_table("stores")
    op.drop_table("organization_members")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_user_id"))

    op.drop_table("auth_sessions")
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
